export const seedExercises = [
  ['bodyweight-squat','Bodyweight Squat','bodyweight','legs',true,['squat','air squat']],
  ['split-squat-bw','Split Squat','bodyweight','legs',true,['stationary lunge']],
  ['reverse-lunge-bw','Reverse Lunge','bodyweight','legs',true,['backward lunge']],
  ['forward-lunge-bw','Forward Lunge','bodyweight','legs',true,['lunge']],
  ['step-up-bw','Step-Up','bodyweight','legs',true,['step up','hotel']],
  ['single-leg-squat-box','Single-Leg Box Squat','bodyweight','legs',true,['pistol regression']],
  ['calf-raise-bw','Calf Raise','bodyweight','legs',true,['standing calf']],
  ['glute-bridge','Glute Bridge','bodyweight','legs',true,['hip bridge']],
  ['single-leg-glute-bridge','Single-Leg Glute Bridge','bodyweight','legs',true,['single leg bridge']],
  ['wall-sit','Wall Sit','bodyweight','legs',true,['wall squat']],
  ['sissy-squat','Sissy Squat','bodyweight','legs',true,['quad squat']],
  ['push-up','Push-Up','bodyweight','push',true,['press up','pushup']],
  ['incline-push-up','Incline Push-Up','bodyweight','push',true,['bench push up']],
  ['decline-push-up','Decline Push-Up','bodyweight','push',true,['feet elevated push up']],
  ['pike-push-up','Pike Push-Up','bodyweight','shoulders',true,['shoulder push up']],
  ['chair-dip','Chair Dip','bodyweight','arms',true,['bench dip','hotel dip']],
  ['chest-dip','Chest Dip','bodyweight','push',true,['parallel bar dip']],
  ['pull-up','Pull-Up','bodyweight','pull',true,['pullup']],
  ['chin-up','Chin-Up','bodyweight','pull',true,['chinup']],
  ['inverted-row','Inverted Row','bodyweight','pull',true,['body row','australian pull up']],
  ['hanging-leg-raise','Hanging Leg Raise','bodyweight','core',true,['leg raise']],
  ['knee-raise-parallel-bars','Knee Raise — Parallel Bars','bodyweight','core',true,['knee raise']],
  ['plank','Plank','bodyweight','core',true,['front plank']],
  ['side-plank','Side Plank','bodyweight','core',true,['lateral plank']],
  ['dead-bug','Dead Bug','bodyweight','core',true,['deadbug']],
  ['bird-dog','Bird Dog','bodyweight','core',true,['bird dog']],
  ['hollow-hold','Hollow Hold','bodyweight','core',true,['hollow body']],
  ['mountain-climber','Mountain Climber','bodyweight','full-body',true,['climber']],
  ['burpee','Burpee','bodyweight','full-body',true,['burpees']],
  ['goblet-squat-kb','Goblet Squat — Kettlebell','kettlebell','legs',false,['gob','goblet','kb squat']],
  ['goblet-squat-db','Goblet Squat — Dumbbell','dumbbell','legs',false,['gob','goblet','db squat']],
  ['kb-swing','Kettlebell Swing','kettlebell','full-body',false,['swing','kb swing']],
  ['kb-deadlift','Kettlebell Deadlift','kettlebell','legs',false,['kb deadlift']],
  ['kb-clean','Kettlebell Clean','kettlebell','full-body',false,['kb clean']],
  ['kb-press','Kettlebell Press','kettlebell','shoulders',false,['kb shoulder press']],
  ['kb-row','Kettlebell Row','kettlebell','pull',false,['kb row']],
  ['turkish-get-up','Turkish Get-Up','kettlebell','full-body',false,['tgu']],
  ['db-step-up','Dumbbell Step-Up','dumbbell','legs',false,['step up']],
  ['db-bench-press','Dumbbell Bench Press','dumbbell','push',false,['db press','chest press']],
  ['incline-db-press','Incline Dumbbell Press','dumbbell','push',false,['incline press']],
  ['one-arm-db-row','One-Arm Dumbbell Row','dumbbell','pull',false,['single arm row','db row']],
  ['db-shoulder-press','Dumbbell Shoulder Press','dumbbell','shoulders',false,['overhead press','db press']],
  ['db-rdl','Dumbbell Romanian Deadlift','dumbbell','legs',false,['db rdl','romanian deadlift']],
  ['db-lunge','Dumbbell Lunge','dumbbell','legs',false,['weighted lunge']],
  ['db-lateral-raise','Dumbbell Lateral Raise','dumbbell','shoulders',false,['side raise']],
  ['db-biceps-curl','Dumbbell Biceps Curl','dumbbell','arms',false,['curl','bicep curl']],
  ['db-triceps-extension','Dumbbell Triceps Extension','dumbbell','arms',false,['tricep extension']],
  ['barbell-back-squat','Barbell Back Squat','barbell','legs',false,['back squat']],
  ['barbell-front-squat','Barbell Front Squat','barbell','legs',false,['front squat']],
  ['barbell-deadlift','Barbell Deadlift','barbell','legs',false,['deadlift']],
  ['barbell-bench-press','Barbell Bench Press','barbell','push',false,['bench press']],
  ['barbell-row','Barbell Row','barbell','pull',false,['bent over row']],
  ['barbell-overhead-press','Barbell Overhead Press','barbell','shoulders',false,['military press','ohp']],
  ['leg-press','Leg Press','machine','legs',false,['machine press']],
  ['single-leg-press','Single-Leg Press','machine','legs',false,['one leg press']],
  ['leg-extension','Leg Extension','machine','legs',false,['quad extension']],
  ['leg-curl','Leg Curl','machine','legs',false,['hamstring curl']],
  ['chest-press-machine','Chest Press — Machine','machine','push',false,['machine chest press']],
  ['lat-pulldown','Lat Pulldown','cable','pull',false,['pulldown']],
  ['seated-cable-row','Seated Cable Row','cable','pull',false,['cable row']],
  ['cable-fly','Cable Fly','cable','push',false,['cable chest fly']],
  ['cable-triceps-pushdown','Cable Triceps Pushdown','cable','arms',false,['pushdown']],
  ['cable-biceps-curl','Cable Biceps Curl','cable','arms',false,['cable curl']],
  ['band-row','Resistance Band Row','band','pull',false,['band row','travel row']],
  ['band-pull-apart','Band Pull-Apart','band','shoulders',false,['pull apart']],
  ['band-external-rotation','Band External Rotation','band','rehabilitation',false,['rotator cuff']],
  ['clamshell','Clamshell','band','rehabilitation',false,['clam shell','glute med']],
  ['terminal-knee-extension','Terminal Knee Extension','band','rehabilitation',false,['tke','knee rehab']],
  ['hip-flexor-stretch','Hip Flexor Stretch','other','mobility',true,['hip stretch']],
  ['thoracic-rotation','Thoracic Rotation','other','mobility',true,['t spine rotation']],
  ['ankle-mobility','Ankle Mobility','other','mobility',true,['ankle dorsiflexion']]
].map(([id,name,equipment,bodyArea,isBodyweight,aliases]) => ({
  id,
  name,
  normalizedName: normalise(name),
  equipment,
  bodyArea,
  isBodyweight,
  aliases,
  isCustom: false,
  isArchived: false,
  createdAt: '2026-07-21T00:00:00.000Z',
  updatedAt: '2026-07-21T00:00:00.000Z'
}));

export function normalise(value) {
  return String(value || '')
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();
}
